# NumPy and its basics


creating a nDarray


In [7]:
# making a numpy nd array
import numpy as np
data=np.random.rand(2,3) # create a 2x3 array
data*=10
data+data
data.shape # dimension of the array
data.size # prints no of elements
data.dtype # prints datatype
data.ndim # prints no of dimensions

2

creating a zero initialised or empty ndarray


In [8]:
# np.empty() it creates an array without initialising its values. The values are whatever is in memory at that time.
data2=np.empty((2,3,2))
data2
# to create arrays initialised wit zeroes
data3=np.zeros((2,3,2))
data3

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

**Type casting** : To convert or cast an array from one dtype to another using ndarray's: _astype()_ method.


In [9]:
arr=np.array([[1,2,3],[4,5,6]])
arr.dtype
float_arr=arr.astype('float64') # type casting
float_arr.dtype 

dtype('float64')

In [ ]:
arr=np.array([['a','B','A'],['4','0','e']])
arr.dtype
#arr.astype('int')# gives error cant cange char to int like this
arr_int=np.vectorize(ord)(arr)
arr_int.dtype
arr_int
# string to int possible only if all are numeric
arr=np.array([['1','2','3'],['4','5','6']])
arr_int=arr.astype('int')
arr_int

array([[1, 2, 3],
       [4, 5, 6]])

we sould be cautious when using numpy.string\_ type as string data in NumPy is fixed size and may truncate input witout warning.


## Arithmetic with NumPy Arrays


This is mostly called as _vectorisation_ by NumPy users. Any arithmetic operation between equal-size arrays applies te operation element wise.


In [17]:
arr=np.array([[1,2,3],[4,5,6]])
mult_arr=arr*arr # element wise multiplication
mult_arr
add_arr=arr+arr # element wise addition
add_arr
arr2=np.array([[0,5,9],[4,5,6]])
sub_arr=arr-arr2 # element wise subtraction
sub_arr

array([[ 1, -3, -6],
       [ 0,  0,  0]])

Arithmetic operations with scalar propagate te scalar arguments to eac elements.


In [ ]:
2/arr # element wise division
arr2/arr # element wise division with another array
arr2**0.5 # square root
arr2>arr # element wise comparison

array([[False,  True,  True],
       [False, False, False]])

## Basic Indexing and Slicing


In [32]:
arr = np.random.randint(0, 100, 10)
arr[5:8]  # slicing includes start index and excludes end index
arr2=arr[5:] # slicing from index 5 to end
arr2[2]=0
print("arr2:", arr2)
arr[8:]=np.array([1,2]) # slicing from index 8 to end
print("arr:", arr)

arr2: [94 80  0 11 94]
arr: [ 3  4  3 66 72 94 80  0  1  2]
